lib/src/signed_video_h26x_common.c, lib/src/signed_video_internal.h
This kind of naming is a technical debt from the past and is
removed in this commit.
=> Refactoring: Removes sei_signed_ from function names

README.md, lib/src/signed_video_h26x_common.c, lib/src/signed_video_internal.h, meson.build, meson_options.txt, tests/README.md, tests/check/check_h26xsigned_sign.c, tests/check/signed_video_helpers.c, tests/check/signed_video_helpers.h, tests/test_checks.sh
This internal function is used to set the size of the |hash_list|.
This comes in handy for check tests to test what happens when the
limit is hit.
Further, by setting the size of the |hash_list| in the tests, the
test-settings meson option is removed since there is no longer a need
to pass in MAX_GOP_LENGTH as define at compile time.
The test_checks.sh script and READMEs have been updated accordingly.
=> Adds set_hash_list_size(...)

lib/src/meson.build, meson.build
The share library signedvideoframework was never added to the config.
Further, the shared library is now versioned.
Also, minor style changes made to lib/src/meson.build.
=> Fixes bug in pkgconfig

lib/src/signed_video_openssl.c
create_rs_private_key() and create_ecdsa_private_key() both always generate new keys. That is, if a key already exists in the specified location it will be overwritten. Previously, no new key was created if one already existed.
=> Always generate new private keys

pre-commit.sh
Previously, it was limited to the src folder.
=> pre-commit.sh now scans all code

lib/src/includes/signed_video_auth.h, lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_internal.h, lib/src/signed_video_h26x_nalu_list.c
'U' now marks an unknown authenticity, for example when a NALU header
is broken.
'_' marks an ignored NALU, which is not hashed and therefore not part
of the signature.
A new SignedVideoFrameType (NALU_TYPE_OTHER) for 'uninteresting' NALUs.
=> Splits validation status 'U' into 'U' and '_'

lib/src/signed_video_h26x_auth.c, lib/src/signed_video_tlv.c, lib/src/signed_video_tlv.h
removes input parameter |self| which is not used.
=> Refactors tlv_find_tag

tests/check/check_h26xsigned_auth.c, tests/check/check_h26xsigned_sign.c, tests/check/meson.build, tests/check/signed_video_helpers.c, tests/check/signed_video_helpers.h
It takes long time to generate private keys during unit tests. Therefore two
copies of private keys are saved. One with algo RSA and one with algo
ECDSA.
=> Only generate private_key if neccesary

lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_internal.h
When a SEI is about to be created everything up to the signature is
written. It is then completed when the signature exists. This means
that SEIs can pile up and storing pointers to these memory slots is
necessary for other signing plugins.
The members payload_ptr and signature_payload_ptr have been removed
since the are not used anymore.
=> Adds a payload_buffer to store ongoing SEIs

lib/plugins/README.md, lib/plugins/meson.build, lib/plugins/threaded-signing/meson.build, lib/plugins/threaded-signing/plugin.c, lib/plugins/unthreaded-signing/meson.build, lib/src/meson.build, meson.build, meson_options.txt, tests/meson.build, tests/test_checks.sh
The new plugin adds a dependency on threads and glib-2.0. It sets up
a worker thread from which the OpenSSL signing is called.
A new meson-option (signingplugin) to select between the two plugins is
added. There is an opation to use the threaded plugin unless we build with
libcheck (threaded_unless_check_dep). Note that the check tests only works
as intended with the unthreaded plugin.
=> Adds a threaded plugin

lib/src/signed_video_h26x_sign.c, lib/src/signed_video_internal.h, lib/src/signed_video_openssl.c, lib/src/signed_video_tlv.c, meson.build, tests/test_checks.sh
- Double free in payload_buffer
- memcmp() of uninitialized data
- Correctly handles meson option signingplugin
- Rewrites openssl_key_memory_allocated()
- Checks has_public_key before memcmp()
- Updates version to v1.1.2
=> Fixes valgrind errors

lib/src/includes/sv_vendor_axis_communications.h, lib/src/signed_video_internal.h, lib/vendors/axis-communications/sv_vendor_axis_communications.c, meson.build, tests/check/check_h26xsigned_auth.c, tests/check/check_h26xsigned_sign.c, tests/check/signed_video_helpers.c, tests/check/signed_video_helpers.h
The certificate chain set by an Axis camera consists of three certificates.
The last one is the public root CA. This certificate is also added to
the library for ease of use when verifying the certificate chain.
Transmitting something that is already present in signed-video-framework
only increases the bitrate. Instead, this last certificate is added to the
certificate chain when decoding the tag. If the original chain did not use
the Axis root CA to sign verification of the chain will fail anyhow.
Tests have been updated.
Version bumped to v1.1.4
=> The public Axis root CA is not added to SEI

lib/src/signed_video_h26x_sign.c, lib/src/signed_video_internal.h, meson.build, tests/check/check_h26xsigned_auth.c, tests/check/check_h26xsigned_sign.c
The light version here means the SV_AUTHENTICITY_LEVEL_GOP, which kicks in
if the hash_list becomes too long; currently at 300 NALUs.
A test in check_h26xsigned_auth.c has been added and the description of
the corresponding test in check_h26xsigned_sign.c has been updated.
=> Fixes a bug when the signing side falls back to light version

lib/plugins/threaded-signing/plugin.c, lib/plugins/unthreaded-signing/plugin.c, lib/src/includes/signed_video_interfaces.h, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_internal.h, meson.build
If signing fails the error is propagated from the plugin to the library
when sv_interface_get_signature() is called, and further to the user.
NOTE: This causes a change in the public API sv_interface_get_signature().
Version is bumped to 1.1.6.
=> Fixes unwanted behavior when signing fails in threaded plugin

lib/src/includes/signed_video_auth.h, lib/src/signed_video_authenticity.c
which indicates to the user that there is a bad mismatch between
versions on signing and validation sides.
=> Adds new state in SignedVideoAuthenticityResult

tests/check/check_h26xsigned_sign.c
It has shown to be flaky with a one byte mismatch in SEI sizes which can
happen if an emulation prevention byte is added. Therefore, the test
allows a slack of one byte.
=> Changes behavior of test sei_increase_with_gop_length

lib/src/includes/signed_video_auth.h, lib/src/signed_video_authenticity.c
This member will be used to communicate the status of the public key validation,
necessary to secure full video authenticity.
=> Adds public_key_validation to signed_video_latest_validation_t

lib/src/includes/signed_video_common.h, lib/src/signed_video_defines.h, lib/src/signed_video_h26x_common.c
which indicates if an error occured in vendor specific code.
=> Adds SV_VENDOR_ERROR to SignedVideoReturnCode

lib/src/signed_video_tlv.c, lib/vendors/axis-communications/sv_vendor_axis_communications.c, lib/vendors/axis-communications/sv_vendor_axis_communications_internal.h
which verifies type and size of the public key and keeps a reference
for later use.
It is called when decoding the public key tag if the product info
identifies Axis Communications as manufacturer.
=> Adds new vendor API set_axis_communications_public_key(...)

lib/vendors/axis-communications/sv_vendor_axis_communications.c, tests/check/check_h26xsigned_auth.c
now updates public_key_validation if the key is not EC instead of returning
an error.
Also adds checking public_key_validation in Axis test.
=> Changes behavior of set_axis_communications_public_key()

lib/vendors/axis-communications/sv_vendor_axis_communications.c
in sv_vendor_axis_communications_t.
=> Properly initializes supplemental_authenticity

lib/src/signed_video_h26x_auth.c, lib/vendors/axis-communications/sv_vendor_axis_communications.c, lib/vendors/axis-communications/sv_vendor_axis_communications_internal.h, tests/check/check_h26xsigned_auth.c
to fetch status of public key used to validate the video.
The API is called before validating the authenticity and is triggered
if Axis is the manufacturer.
=> New vendor API get_axis_communications_supplemental_authenticity

lib/vendors/axis-communications/sv_vendor_axis_communications.c
with an incomplete skeleton implementation. Only verifies the certificate
chain.
Further, the trusted root CA has change name to kTrustedAxisRootCA and is
converted to X.509 form at setup and stored in a new member |trusted_ca|.
=> New vendor API verify_and_parse_certificate_chain

lib/vendors/axis-communications/sv_vendor_axis_communications.c
which turns the serialized attestation data, part of the SEI, into an
attestation report.
=> New Axis vendor function deserialize_attestation

lib/vendors/axis-communications/sv_vendor_axis_communications.c
Now truly skips setting the public key if previous validation failed.
Further, the check if pointer to public_key is the same is no guarantee
the keys differ, and comparing the content is not enough either since
the pointers may differ. To be completely safe, we always check the
size and type of the public_key.
=> Fixes a bug in set_axis_communications_public_key

lib/src/signed_video_h26x_common.c, lib/src/signed_video_internal.h, meson.build, tests/check/check_h26xsigned_auth.c
where global_gop_counter_is_synced was not reset. This caused incorrect
behavior when seeking in a file. Tests were not implemented correctly,
missing this flaw, but have now been updated.
Version is bumped to v1.1.8.
=> Fixes a bug in signed_video_reset(...)

lib/src/includes/signed_video_auth.h, lib/src/signed_video_authenticity.c, tests/check/check_h26xsigned_auth.c
and explicity states, in the description, that the timestamps are
measured in microseconds. The check tests have been updated accordingly.
=> Adds first and last timestamps to the accumulated authenticity

lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_internal.h, lib/src/signed_video_h26x_sign.c, tests/check/check_h26xsigned_sign.c, tests/check/nalu_list.c, tests/check/signed_video_helpers.c
This prevents the signing side from hashing an incoming Signed
Video SEI frame.
In addition, pre-commit.sh made formatting changes to nalu_list.c.
=> Extends parse_nalu_info() with is_auth_side parameter

.github/workflows/meson-build.yml, .github/workflows/meson-full-build.yml, lib/src/signed_video_openssl.c, lib/vendors/axis-communications/sv_vendor_axis_communications.c
Some APIs have been deprecated in OpenSSL 3.0. In selected places,
the deprecated APIs have been replaced under a define to make it build
also in older versions.
The temporary OpenSSL build in workflow is removed.
=> Uses define to separate deprecated OpenSSL code

lib/src/includes/signed_video_sign.h, lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_internal.h, lib/src/signed_video_h26x_nalu_list.c, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_internal.h, lib/src/signed_video_tlv.c, lib/vendors/axis-communications/sv_vendor_axis_communications.c, lib/vendors/axis-communications/sv_vendor_axis_communications_internal.h, tests/check/check_h26xsigned_auth.c, tests/check/check_h26xsigned_sign.c, tests/check/nalu_list.c, tests/check/signed_video_helpers.c
This is a new API for the signing side which configures the Signed
Video session to produce SEIs with or without emulation prevention.
The default behavior is with emulation prevention turned on.
Two new tests have been added; one on the signing side to compare
SEIs w/wo emulation prevention, and one on the validation side to
verify that validation works even if emulation prevention bytes are
added later.
In addition, a name change of a member is done from tmp_tlv_memory
to nalu_data_wo_epb, since the entire nalu_data is copied instead
of just the tlv part.
=> Adds a setter to write SEIs w/wo emulation prevention

lib/plugins/threaded-signing/plugin.c, tests/check/check_h26xsigned_auth.c, tests/check/check_h26xsigned_sign.c
This solves the issue of failed signing if the signing
functionality was temporarily blocked when Signed Video made
the request.
Now incoming hashes are put in a queue, from which the signing
thread picks hash by hash.
A test has been added for this case.
=> Adds a queue in threaded-signing/plugin

lib/src/signed_video_h26x_nalu_list.c, lib/src/signed_video_h26x_nalu_list.h, tests/check/check_h26xsigned_auth.c, tests/check/check_h26xsigned_sign.c, tests/check/nalu_list.c, tests/check/nalu_list.h
In many places the strings are single characters and there is no
point in overdoing things to keep them as strings.
=> Replaces character strings with single char

lib/plugins/threaded-signing/plugin.c, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_internal.h, meson.build
when tearing down a signing thread. If signing is active when
closing down the plugin, memory might be freed that later is used.
This commit waits for an ongoing signing to complete before
freeing memory.
=> Fixes potential segfault

lib/src/signed_video_internal.h, lib/vendors/axis-communications/sv_vendor_axis_communications.c, meson.build
For vendor Axis Communications, two intermediate certificates
are expected and a third root CA. Before this commit a check
for bitexactness of the root CA certificate was done, which
could cause missing out the certificate chain, even though
validation would pass.
Now the check only verifies there are in total three
certificates in the chain and the first two are added to the
SEI.
Bumps version to v1.1.29.
=> Adds all intermediate certificates

lib/plugins/threaded-signing/plugin.c, lib/plugins/unthreaded-signing/plugin.c, lib/src/includes/signed_video_openssl.h, lib/src/signed_video_h26x_common.c, lib/src/signed_video_openssl.c
since it is simply a macro that adds debug info __FUNC__ and
__LINE__ to a normal free() call.
The code now use free() throughout.
=> Removes uses of OPENSSL_free

lib/src/includes/signed_video_openssl.h, lib/src/includes/signed_video_sign.h, lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_openssl.c, lib/src/signed_video_tlv.c, tests/check/check_h26xsigned_auth.c, tests/check/check_h26xsigned_sign.c, tests/check/signed_video_helpers.c
More precisely, removes usage of the algo member in
signature_info_t since that information can be extracted from the
key pair. The member itself is NOT removed due to backward
compatibility.
A new function for setting the private key has been added
temporarily until the old one is deprecated.
=> Removes usage of sign_algo_t in code

lib/plugins/threaded-signing/plugin.c, lib/plugins/unthreaded-signing/plugin.c, lib/src/includes/signed_video_openssl.h, lib/src/includes/signed_video_signing_plugin.h, lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_openssl.c, tests/check/check_h26xsigned_auth.c
instead of PEM format. This saves some operations when signing a
hash, since the EVP_PKEY otherwise has to be created from the PEM
format for every signature.
At the same time as the conversion is done, memory for the largest
possible signature is allocated.
A new struct pem_pkey_t to store a private or public key in PEM
format has been added. This struct is used in the new version of
threaded signing plugin at init (optional by user).
Further, two new openssl helpers are added openssl_free_key() and
openssl_private_key_malloc(), where the latter more or less
replaces openssl_signature_malloc() (now removed).
=> Stores the private key in EVP_PKEY format

lib/src/includes/signed_video_openssl.h, lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_internal.h, lib/src/signed_video_openssl.c, lib/src/signed_video_tlv.c, lib/vendors/axis-communications/sv_vendor_axis_communications.c, lib/vendors/axis-communications/sv_vendor_axis_communications_internal.h, tests/check/check_h26xsigned_auth.c
instead of PEM format in the signature_info struct. This saves some
operations when verifying a signature, since the EVP_PKEY otherwise
has to be created from the PEM format for every verification.
The PEM format public key is intermediately stored in the pem_public_key
member of signed_video_t since the PEM format is written to/read from
the SEIs.
Further, a new openssl helpers are added openssl_public_key_malloc(),
where the latter turns a PEM public key into an EVP_PKEY object.
=> Stores the public key in EVP_PKEY format

lib/src/includes/signed_video_openssl.h, lib/src/signed_video_openssl.c
To further reduce number of openssl operation the lib keeps
the private and public keys in an algorithm context which
can be used directly when signing or verifying.
=> Uses EVP_PKEY_CTX instead of EVP_PKEY

lib/src/includes/signed_video_openssl.h, lib/src/signed_video_openssl.c, lib/src/signed_video_openssl_internal.h, lib/src/signed_video_tlv.c
This commit removes two functions; openssl_key_memory_allocated()
and openssl_get_algo_of_public_key(). It is safe to remove
the first one from the public header file since it by nature is
a helper function.
=> Removes unused functions

lib/src/includes/signed_video_openssl.h, lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_internal.h, lib/src/signed_video_openssl_internal.h, lib/src/signed_video_tlv.c, tests/check/check_h26xsigned_auth.c
The public header file signed_video_openssl.h is primarily meant
for signing plugins + signing users that need a helper function
to generate a software private key for testing. Everything else
are APIs used by the library, hence can/should be placed in an
internal header file.
=> Moves some openssl declarations to internal

lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_openssl.c, lib/src/signed_video_openssl_internal.h, lib/src/signed_video_tlv.c, tests/check/check_h26xsigned_auth.c
Internal functions should return svi_rc instead of
SignedVideoReturnCode.
=> Refactoring signed_video_openssl

lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_internal.h, lib/src/signed_video_openssl.c, lib/src/signed_video_openssl_internal.h
To be able to support arbitrary hash algorithms when hashing NAL
Units, the library needs to use EVP_MD_CTX. If so, it is
possible to set the EVP_MD to use, for example, EVP_sha256().
The context is stored in the |crypto_handle|. Separate calls for
openssl 3.0 or openssl 1.1 was used, but the openssl 3.0
functions already existed in openssl 1.1, hence they can be used
for both. This change is made in this commit.
To use the context, every hash needs to do init/update/finalize
instead of the short-cut function SHA256(). Using short-cut
functions will not scale to arbitrary hashing algorithms.
Some internal functions needed the |crypto_handle| as input and
that change is made in this commit.
=> Prepares for arbitrary hash algorithm

.github/workflows/meson-build.yml, lib/src/includes/signed_video_sign.h, lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_internal.h, lib/src/signed_video_openssl.c, lib/src/signed_video_openssl_internal.h, tests/check/check_h26xsigned_sign.c
To customize usage of hash algorithms a new setter is added.
This new function sets the hashing algorithm, used to hash NAL
Units, given a name or OID that OpenSSL can interpret. If the
hash algorithm is not set, SHA256 is used.
A change of hash algorithm cannot be applied once the session has
started hashing NAL Units. Therefore a new member
|signing_started| has been added.
Basic signing tests is added.
NOTE that the validation side is not updated. The library still
assumes the video is hashed with SHA256. Transferring the
knowledge of which hash algorithm is in use is done in separate
commits.
=> Adds a setter for hash algorithm

lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_openssl.c, lib/src/signed_video_openssl_internal.h
Since the hash algorithm can be arbitrary there is a need to know
the hash size when for example allocating memory.
A getter for this has been added and the size is extracted from
the EVP_MD when a hash algo is set.
=> Adds hash size getter

lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_internal.h, lib/src/signed_video_h26x_nalu_list.c, lib/src/signed_video_h26x_nalu_list.h, lib/src/signed_video_internal.h, lib/src/signed_video_tlv.c, tests/check/signed_video_helpers.c
The hash algorithm is not known until the first SEI arrives.
Therefore, the hashable data is copied and kept until the
hash algo is known. When the first SEI arrives, all stored
NALUs are re-run and hashed.
The side effect is that when the video is not signed the
memory impact becomes larger.
Further, the hash_and_add_for_auth() function now takes
a list item rather than the h26x_nalu_t struct as input.
=> Solves validation side with arbitrary hash algo

tests/check/check_h26xsigned_auth.c, tests/check/check_h26xsigned_sign.c, tests/check/signed_video_helpers.c, tests/check/signed_video_helpers.h
The tests now take a function pointer as input instead of
sign_algo_t. The test scope has been reduced as well. RSA
keys have been moved to "Special cases".
=> Changes tests to use new key generation APIs

lib/src/includes/signed_video_openssl.h, lib/src/signed_video_openssl.c
There is no gain in using a struct for key paths and buffers.
Instead use the pem_pkey_t struct and separate the path.
=> Removes key_paths_t

lib/plugins/threaded-signing/plugin.c, lib/src/includes/signed_video_openssl.h, lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_common.c, lib/src/signed_video_openssl.c, lib/src/signed_video_openssl_internal.h, lib/src/signed_video_tlv.c, tests/check/check_h26xsigned_auth.c
Renames members of pem_key_t from pkey to key to avoid
misunderstanding with EVP_PKEY objects.
Updated some descriptions and comments and removed unnecessary
includes.
=> Cleanups in openssl

lib/plugins/README.md, lib/plugins/threaded-signing/plugin.c, lib/plugins/unthreaded-signing/plugin.c, lib/src/includes/signed_video_openssl.h, lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_internal.h, lib/src/signed_video_openssl.c, lib/src/signed_video_openssl_internal.h, tests/check/check_h26xsigned_auth.c
To add a clearer separation between the signing side and the
validation side in the code the signature_info_t is split
into one siging_info_t part and one for validation.
This commit address the signing part only and a new struct
signing_info_t is added, which holds the hash to sign, the
private key and the generated signature.
Three functions now use this new struct openssl_sign_hash(),
openssl_private_key_malloc() and
openssl_read_pubkey_from_private_key().
The change affects the signing plugins in particular. The src
code still has a member signature_info, which is used and the
necessary parts have been copied from signing_info for now.
=> Adds a new struct to replace signature_info_t

lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_internal.h, lib/src/signed_video_openssl.c, lib/src/signed_video_openssl_internal.h
The verify hash function now takes a sign_or_verify_data_t
struct as input.
=> Changes openssl_verify_hash

lib/src/includes/signed_video_openssl.h, lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_openssl.c, lib/src/signed_video_openssl_internal.h, lib/src/signed_video_tlv.c
The last function, openssl_public_key_malloc(), now takes the
new sign_or_verify_data_t as input.
=> Removes last dependency on signature_info_t in openssl

lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_internal.h
The hash size has more or less been implicitly used when
hash function wrappers are used. They now take a size as
input.
=> Adds hash size as input to hash functions

lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_common.c, lib/src/signed_video_internal.h, lib/src/signed_video_tlv.c
Adds a verify_data member for storing the public key etc
for verifying the signature.
Renames sign_data_create and sign_data_free, since it now also
is used by verify_data. The free function now frees the key as
well, which was not needed for sign_data, since it is handled
by the signing plugin.
=> Removes last dependency on signature_info_t in code

tests/check/check_h26xsigned_auth.c, tests/check/check_h26xsigned_sign.c, tests/check/signed_video_helpers.c, tests/check/signed_video_helpers.h, tests/check/test_stream.c, tests/check/test_stream.h
Now takes a single character as type instead of a string.
Related functions in signed_video_helper.s has been updated
as well.
=> Updates test_stream_item_check_type()

tests/check/test_stream.c, tests/check/test_stream.h
Some functions are not used outside test_stream.c. These
have been made static instead. The print functions are still
declared in the header file for manual debug purposes.
=> Makes some functions static

tests/check/test_stream.c, tests/check/test_stream.h
Since the dummy nalus are not used outside test_stream.c
make them static and remove extern declaration in header file.
Also made some changes to descriptions.
=> Makes dummy nalus static

lib/src/meson.build, lib/src/signed_video_openssl.c, lib/vendors/axis-communications/sv_vendor_axis_communications.c
OpenSSL version older than 3.0.0 has been deprecated. Therefore,
all code for 1.1.1 is removed. The validation side has not been
limited by the older version, so old recordings are still
backwards compatible.
=> Support only OpenSSL 3

tests/check/check_h26xsigned_auth.c, tests/check/check_h26xsigned_sign.c, tests/check/meson.build, tests/check/test_helpers.c, tests/check/test_helpers.h
To separate from the src code, renames the helper files to
test_helpers.{c, h}
=> Renames signed_video_helpers

lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_internal.h, lib/src/signed_video_openssl.c
Since the library no longer use internal return codes
mapping functions between them has been removed.
=> Removes svi_rc sv_rc helpers

lib/src/signed_video_authenticity.c, lib/src/signed_video_authenticity.h, lib/src/signed_video_defines.h, lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_internal.h, lib/src/signed_video_h26x_nalu_list.c, lib/src/signed_video_h26x_nalu_list.h, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_internal.h, lib/src/signed_video_openssl.c, lib/src/signed_video_openssl_internal.h, lib/src/signed_video_tlv.c, lib/src/signed_video_tlv.h, lib/vendors/axis-communications/sv_vendor_axis_communications.c, lib/vendors/axis-communications/sv_vendor_axis_communications_internal.h
The typedef svrc_t is the same as SignedVideoReturnCode, but
should be used with the distinction between internal and public
interfaces.
=> Renames svi_rc to svrc_t

lib/src/signed_video_h26x_common.c, lib/src/signed_video_internal.h
The signed_video_create function now initilializes members in
the same order as they appear in the object.
Also moved some resets to gop_info_reset() which in addition
has been made static.
=> Organizes signed_video_create

lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_internal.h
The member in signed_video_t is not used anywhere, since it
is part of validation_flags.
=> Removes signing_present

lib/plugins/unthreaded-signing/plugin.c, lib/src/includes/signed_video_signing_plugin.h, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_internal.h, tests/check/check_signed_video_sign.c
Updated the signing process to support generating golden SEIs in a multi-threaded
environment. Finalizing SEI is no longer done in the same function, allowing signing
to occur in a separate thread. Users are now responsible for ensuring SEI completion
before fetching the signature from the signing plugin.
=> Support multi-threaded signing for golden SEI generation

lib/plugins/unthreaded-signing/plugin.c, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_internal.h, tests/check/check_signed_video_sign.c
- Revert "Revert "Support multi-threaded signing for golden SEI generation(#205)"
- Disable test for blocked signature
=>  Disable test for blocked signature

lib/vendors/axis-communications/sv_vendor_axis_communications.c
The public key was interpreted as an EVP_PKEY instead of an
EVP_PKEY_CTX.
=> Fixes a bug when validating Signed Video from Axis

lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_internal.h, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_internal.h, lib/src/signed_video_tlv.c
GENERAL TAG: Enhance NALU processing by copying NALUs to the hash list only
if they are not SEI frames. This allows processing in one shot if we have
the complete list of NALUs or by updating an ongoing hash.
=> Write NALUs in the GOP to GENERAL

tests/check/test_helpers.c
The private key generating functions have quite long names.
This commit adds a short cut name to them in tests.
=> Adds short name to key generators

tests/check/check_signed_video_sign.c, tests/check/test_helpers.c, tests/check/test_helpers.h
The ep_before_signing controls emulation prevention bytes.
=> Adds a new test setting member

lib/src/signed_video_tlv.c, tests/check/check_signed_video_auth.c, tests/check/check_signed_video_sign.c, tests/check/test_helpers.c, tests/check/test_helpers.h
Now it fully relies on the setting and makes all necessary
changes to it.
Also, fixes a bug when using other hashes than the default one.
The NALU hash position is now correctly updated upon decoding the
crypto tag.
=> Test function for getting initialized session has changed

tests/check/check_signed_video_sign.c, tests/check/test_helpers.c, tests/check/test_helpers.h
instead of starting from scratch with signed_video_create().
=> Uses get_initialized_signed_video() on signing side

tests/check/check_signed_video_auth.c, tests/check/test_helpers.c
instead of starting from scratch with signed_video_create().
=> Uses get_initialized_signed_video() on auth side

lib/plugins/threaded-signing/plugin.c
If a session is closed while a hash is being signed the generated
signature returns after teardown. The signature is then still
added to the plugin output buffer which could be picked up by a
new session.
This commit solves that issue by only adding generated signatures
if the session is still active. Further, new session ids are now
unique until the number wraps around.
=> Fixes a bug in the threaded plugin running in central mode

meson.build, meson_options.txt
This option enables printing by setting a compile time define;
PRINT_DECODED_SEI. No prints have yet been implemented.
=> Adds a meson option to print decoded SEIs

lib/src/signed_video_h26x_common.c, lib/src/signed_video_internal.h, tests/check/check_signed_video_sign.c
useful for hashes and signatures. Currently only available under
the PRINT_DECODED_SEI flag.
=> Adds a helper function to print data in hex format

lib/src/includes/signed_video_helpers.h, lib/src/meson.build, lib/src/signed_video_h26x_common.c, lib/src/signed_video_tlv.c, tests/check/check_signed_video_sign.c
which can be used to decode and parse the data of a SEI. Currently
only prints the SEI data itself and the reserved byte. Prints for
decoded TLV tags are out of scope for this commit.
=> Implements signed_video_parse_sei(...)

lib/src/legacy/legacy_tlv.c, lib/src/signed_video_tlv.c
Under the PRINT_DECODED_SEI flag prints the content of a Product
Information tag present in a SEI. This is applied to both the
current and the legacy code.
=> Prints decoded information of the product info tag

lib/src/legacy/legacy_tlv.c, lib/src/signed_video_tlv.c
Under the PRINT_DECODED_SEI flag prints the content of an Arbitrary
Data tag present in a SEI. This is applied to both the current and
the legacy code.
=> Prints decoded information of the arbitrary data tag

lib/src/legacy/legacy_tlv.c, lib/src/signed_video_tlv.c
Under the PRINT_DECODED_SEI flag prints the content of a Signature
tag present in a SEI. This is applied to both the current and the
legacy code.
=> Prints decoded information of the signature tag

lib/src/legacy/legacy_tlv.c, lib/src/signed_video_openssl.c, lib/src/signed_video_openssl_internal.h, lib/src/signed_video_tlv.c
Under the PRINT_DECODED_SEI flag prints the content of a Crypto
Information tag present in a SEI. This is applied to both the
current and the legacy code.
In addition, adds a helper function to convert a hash algorithm
on OID serialized form to a readable string.
=> Prints decoded information of the crypto info tag

lib/src/signed_video_h26x_common.c
It was previously not stored, but it only affected some prints
=> Writes hash size to item

lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_internal.h, lib/src/signed_video_openssl.c
Also, removes the existing prints of the hash to sign/verify.
=> Prints the hash and signature when signing and verifying

lib/src/includes/signed_video_sign.h, lib/src/signed_video_h26x_sign.c, tests/check/check_signed_video_auth.c, tests/check/check_signed_video_sign.c, tests/check/test_helpers.c
This means that the user now can know how many SEIs are still in process
of being signed.
Tests have been updated with checks for correct numbers in queue.
=> Adds num_pending_seis parameter to signed_video_get_sei(...)

lib/src/signed_video_h26x_auth.c
The next I-frame is no longer part of the hash list as the link
hash. This commit fixes one check where it is accounted for.
=> Wrong when losing an entire GOP

lib/src/signed_video_h26x_nalu_list.c
This is done by setting the used_in_gop_hash flag.
=> Marks also missing items to belong to a GOP

lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_nalu_list.c, lib/src/signed_video_h26x_nalu_list.h
This makes sure to collect statistics correctly if several GOPs
are being validated in the same go.
=> Keeps the GOP hash flag until stats collected

lib/src/signed_video_h26x_sign.c, lib/src/signed_video_internal.h
If SEIs are available, but could not be fetched with the
signed_video_get_sei(...) API, since it would otherwise break the
H.26x standard, make sure to override the sanity check.
=> Only sanity check available SEIs if deprecated API

tests/check/check_signed_video_auth.c, tests/check/check_signed_video_sign.c, tests/check/test_helpers.c
This has a large impact on the tests. First, all tests streams have
been increased with a 'P' to make sure that there is a NAL Unit to
prepend a SEI with.
Secondly, the SEIs are now delayed by one frame, which affects the
validation statistics. In particular, all validations get a
pending NAL Unit (the I-frame).
Thirdly, since validation is triggered upon 2 I-frames, essentially
all validations start with an unsigned GOP. Fixing this, will be
done in a separate commit.
The common test description has been updated with these changes.
Further, almost all tests now have the same structure describing
the validation flow.
=> Tests call signed_video_get_sei() before add for signing

tests/check/check_signed_video_auth.c, tests/check/check_signed_video_sign.c, tests/check/test_helpers.c, tests/check/test_helpers.h
As a first step to change from generating new signing keys for
every test to a pre-created signing key, a boolean member is used
to select between EC and RSA.
=> Changes to boolean for key creation

tests/check/check_signed_video_auth.c, tests/check/check_signed_video_sign.c, tests/check/test_helpers.c, tests/check/test_helpers.h
The function still generates the requested signing key.
Implementation and key files to be added in a separate commit.
=> Adds an empty private key reader function

lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_internal.h, lib/src/signed_video_h26x_nalu_list.c, lib/src/signed_video_h26x_nalu_list.h, tests/check/check_signed_video_auth.c
With the transition to the new linking principle now complete, this commit removes
flags that were needed for the previous approach. These flags are no longer relevant
or used in the current implementation.
Change-Id: I6adb35497df6a7845225534a9ac4fe18980007c7
=> Remove unused flags from old linking approach

lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_internal.h, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_internal.h
These APIs are no longer needed as recursive hash is not used.
=> Remove reset_gop_hash and update_gop_hash APIs

lib/src/legacy/legacy_h26x_auth.c, lib/src/legacy/legacy_h26x_common.c, lib/src/legacy/legacy_h26x_internal.h, lib/src/legacy/legacy_h26x_nalu_list.c, lib/src/legacy/legacy_h26x_nalu_list.h
At validation starts, SEIs are not synchronized with an I-frame. It is
unknown how many SEIs that cannot be used to validate frames, since
they sign GOPs not present.
This commit loops through all possible validation cases with the SEI
by temporarily use tmp_validation_status and a few more flags. The
validation_status is then updated when the SEI is not feasible to use
in a validation.
=> Synchronizes SEIs for legacy code

tests/check/check_signed_video_auth.c
The library is not working for file exports where arbitrary number
of useless SEIs are present in the beginning. A useless SEI is a
SEI that actually belongs to a snippet of the stream present before
the recording.
The library can handle one such SEI, but not two. Therefore, this
commit adds two tests that have two useless SEIs in the beginning,
one for a stream start and one for a file export.
The test helper function generate_delayed_sei_list() has been
extended with two more GOPs to catch if tests are recovered to
produce "valid" outputs.
=> Adds two tests with two useless SEIs

lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_nalu_list.c, lib/src/signed_video_h26x_nalu_list.h
All operations when validating a GOP is done on tmp_validation_status.
A function that either updates validation_status or resets
tmp_validation_status has been added.
Operations that are done by the authenticity_report, like removing
validated items, are done on validation_status.
This commit does not change any behavior.
=> Validates using tmp_validation_status

lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_nalu_list.c, tests/check/check_signed_video_auth.c
When validating a stream/recording SEIs are not synchronized
with the I-frames. There can for examples be multiple SEIs
in the beginning that were generated by frames prior to the
frames present in the recording.
This commit test validates each SEI for every possible way
before either accepting or discarding it.
=> Synchronizes SEIs at beginning of a recording

lib/src/includes/signed_video_sign.h, lib/src/legacy/legacy_h26x_common.c, lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_internal.h, lib/src/signed_video_h26x_sign.c, tests/check/check_signed_video_sign.c, tests/check/test_helpers.c
All signing tests have been enabled.
In addition, has_reference_hash is correctly reset, emulation
prevention API returns NOT SUPPORTED for AV1 and some comment
cleanup in signing tests.
=> Implements signing for AV1

tests/check/check_signed_video_auth.c, tests/check/legacy_test_data.c
All normal tests pass, but legacy stream still has no AV1 OBUs.
The legacy validation has been verified to work through manual
tests.
=> Updates validation side with AV1

lib/src/signed_video_h26x_common.c, lib/src/signed_video_internal.h, lib/src/signed_video_openssl.c
Also removes the dead code of the gop_hash_init from the
deprecated recursive procedure.
=> Initializes the GOP hash with a salt

meson.build, meson_options.txt, tests/check/test_helpers.c
Not all situations can use pre-generated keys, therefore, an
option to override that and generate keys for every test has
been added.
=> Adds back the possibility to use generated keys in tests

lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_internal.h, lib/src/signed_video_h26x_nalu_list.c, tests/check/check_signed_video_auth.c
- Unsigned report is only present in the accumulated one
- If number of GOPs exceeds 20 all units are hashed with the
default hash algo
- Signed stream is only reported once in latest
This change avoids producing an "unsigned" GOP in the beginning
if that one does not include a SEI/OBU Metadata.
Tests have been updated accordingly.
=> Updates authenticity report

lib/src/legacy/legacy_h26x_auth.c
that is, only reporting unsigned in accumulated, and signed only
once.
=> Adds same auth report logic to legacy code

lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_internal.h, lib/src/signed_video_h26x_nalu_list.c, lib/src/signed_video_h26x_sign.c, lib/src/signed_video_internal.h
The second_hash member is no longer required as linking is now handled
with a separate hash in the TLV instead of being part of the hash list.
Consequently, the I-frame is now hashed in only one way. Additionally,
the has_reference_hash member has been removed as part of this cleanup.
=> Remove unused second_hash and has_reference_hash members

lib/vendors/axis-communications/sv_vendor_axis_communications.c, tests/check/check_signed_video_sign.c
The attestation part is optional, depending on provisioning
method. This step changes the setter API to require certificate
chain in call, but not attestation.
=> Requires certificate chain to be set.

lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_common.c, lib/src/signed_video_internal.h
Removed the validate_after_next_nalu member as it is no longer required for the current validation process.
Change-Id: I7259d2a858e740dc8cd649f74ef2aefd4dc28b2d
=> Remove validate_after_next_nalu member

tests/check/check_signed_video_sign.c, tests/check/test_helpers.c, tests/check/test_helpers.h
Tests can now run without Axis, with Axis attestation and Axis
factory provisioned. The latter means that the public key is
part of the leaf certificate.
Helper function to read a certificate chain is added.
=> Adds a new vendor axis mode for tests

lib/src/signed_video_h26x_auth.c, lib/src/signed_video_h26x_common.c, lib/src/signed_video_h26x_internal.h, lib/src/signed_video_internal.h
The gop_state struct is now obsolete following the removal of the state
machine. Its functionality has been replaced by validation_flags. Most
members of gop_state are unnecessary and have been removed. Any remaining
relevant members have been migrated to validation_flags.
=> Remove gop_state struct and migrate relevant members

lib/vendors/axis-communications/sv_vendor_axis_communications.c, lib/vendors/axis-communications/sv_vendor_axis_communications_internal.h
if Axis factory provisioning is used. A helper function to read
the public key from the leaf certificate is added.
=> Adds a getter for the public key

tests/check/check_signed_video_auth.c, tests/check/check_signed_video_sign.c
The tests have been modified with incorrect expectations to pass.
Correct expectations will be enabled once the feature is
implemented.
Two authentication tests require some additional functionality
and are currently not run at all.
=> Adds tests for signing partial GOPs

lib/src/sv_common.c, lib/src/sv_internal.h, tests/check/check_signed_video_auth.c, tests/check/check_signed_video_sign.c, tests/check/test_helpers.c, tests/check/test_helpers.h
In addition adds a |signing_frequency| member in signed_video_t
which is not used in practise. It will have an impact when the
library supports signing multiple GOPs.
=> Adds the possibility to delay SEIs when creating test stream

lib/src/includes/signed_video_sign.h, lib/src/sv_internal.h, lib/src/sv_sign.c, tests/check/check_signed_video_auth.c, tests/check/check_signed_video_sign.c, tests/check/test_helpers.c, tests/check/test_helpers.h
The member name has changed from max_signing_bu because it is
easier for the user to count frames rather than Bitstream
Units.
API tests have been added.
=> Adds a setter for max_signing_frames

lib/src/sv_internal.h, lib/src/sv_tlv.c
The flag triggered_partial_gop is used to communicate if the SEI
was triggered by a partial GOP. It is needed for the validation
side to know that a complete GOP is not expected. If this is not
communicated there will be faulty detection of missing Bitstream
Units.
The general tag TLV has been updated with the flag. No need to
bump up the version of that tag since the default value is
'false' and what is done historically.
=> Adds new member to gop_info_t

lib/src/sv_common.c, lib/src/sv_sign.c
This will simplify updating the linked hash when signing
partial GOPs.
=> Moves update_linked_hash to hash functions

lib/src/sv_internal.h, lib/src/sv_sign.c
The member gop_hash_off was unused in the codebase and has been removed.
=> Remove unused member gop_hash_off

lib/src/sv_internal.h, lib/src/sv_sign.c, tests/check/check_signed_video_auth.c, tests/check/check_signed_video_sign.c
Adds a counter for number of frames in a partial GOP. This is
needed since the setting of partial GOP size is determined in
frames instead of Bitstream Units for ease of use.
Signing side tests have been updated. Further, tests now also
verifies signing partial GOPs for multi-sliced streams.
Note that the validation side cannot handle signed partial
GOPs yet.
=> Enables signing partial GOPs

lib/src/sv_common.c, lib/src/sv_internal.h, lib/src/sv_sign.c, lib/src/sv_tlv.c
The gop_hash member in the gop_info_t struct was unused and has
been removed.
=> Remove unused member gop_hash from gop_info_t struct

lib/src/sv_internal.h, lib/src/sv_sign.c, lib/src/sv_tlv.c
The member signature_hash_type was unused in the codebase and
has been removed
=> Remove unused member signature_hash_type

lib/src/sv_auth.c
When preparing for validation the number of BUs marked now
depends on the number of sent BUs if a partial GOP was triggered.
If validation fails, the number of marked items are extended to
avoid aborting validation too early.
Last, when verifying individual hashes the number of verified
ones will not exceed the number sent.
=> Updates use_in_gop_hash wrt partial GOPs

lib/src/includes/signed_video_auth.h, lib/src/legacy/legacy_auth.c, lib/src/legacy/legacy_common.c, lib/src/legacy/legacy_tlv.c, lib/src/sv_auth.c, lib/src/sv_authenticity.c, lib/src/sv_common.c, lib/src/sv_internal.h, lib/src/sv_sign.c, lib/src/sv_tlv.c
When the signed_video_t object is created the
signed_video_product_info_t is statically allocated where
all strings have a preset fixed length of 255 bytes. This
makes it more clear to the user that strings longer than
255 characters will be truncated.
In the TLV, the strings are now encoded without null-terminated
characters. The operation is backward compatible.
=> Statically allocates memory for product info

lib/src/sv_sign.c
A copy-paste error computed a much larger size than necessary
for the SEIs.
=> Computes correct sei size for memory allocation

lib/src/sv_internal.h, lib/src/sv_sign.c, lib/src/sv_tlv.c, lib/vendors/axis-communications/sv_vendor_axis_communications.c
This commit lets the TLV code handle vendor tags. The Axis
vendor tag is now part of the optional tags and if built
without Axis Communication, the encoder will be empty and
by default not be added.
=> Moves Axis vendor tag to optional tags

lib/src/sv_common.c, lib/src/sv_internal.h, tests/check/check_signed_video_common.c
Add functions to convert between Unix and 1601-based timestamps
Change-Id: I0baf3c9a4b1d34ecde114fcb7344b4b97785ec21
=> Add functions to convert between timestamps

lib/plugins/threaded-signing/plugin.c, lib/plugins/unthreaded-signing/plugin.c, lib/src/includes/signed_video_sign.h, lib/src/includes/signed_video_signing_plugin.h, lib/src/sv_sign.c
Now declarations and definitions are kept until complete removal.
=> Fixes two deprecated APIs.

.github/workflows/meson-build.yml, lib/src/meson.build, lib/src/sv_internal.h, lib/src/sv_onvif.c, lib/src/sv_onvif.h, lib/src/sv_sign.c
When the signing session runs as ONVIF Media Signing, media
signing is generating the SEIs. Ask the media signing sesssion
for the SEIs if active.
This commit adds a stub of the ONVIF public API if ONVIF
Media Signing is not installed.
=> Gets SEIs from ONVIF session if active

lib/src/sv_onvif.c, lib/src/sv_onvif.h, lib/src/sv_sign.c
The hash_algo parameter is passed on to ONVIF if Media Signing
is active.
=> Passes on setter to ONVIF if active

lib/src/sv_auth.c, lib/src/sv_onvif.c, lib/src/sv_onvif.h
This commits reregisters the Bitstream Units into the ONVIF
session if that has been detected.
Stubs for the ONVIF API and a definition of the auth_report
has also been added.
=> Reregister BUs with ONVIF if active

lib/src/sv_auth.c, lib/src/sv_onvif.c, lib/src/sv_onvif.h
If Media Signing has been detected, the incoming Bitstream
Units are then passed on to ONVIF API. If an authenticity
has been received that report is freed. Copying the content
is done in a separate commit.
In addition adds necessary stub for freeing the report.
=> Passes on BUs to ONVIF Media Signing if active

lib/src/sv_onvif.c, lib/src/sv_onvif.h, lib/src/sv_sign.c
The BU data  is passed on to the ONVIF Media Signing API using `onvif_media_signing_add_nalu_for_signing`
if ONVIF Media Signing is available.# Please enter the commit message for your changes.
Change-Id: I0b5c518692d03b494c78e61f62cb20f650df2511
=> Passes on BU for signing to ONVIF if available

lib/src/sv_auth.c, lib/src/sv_authenticity.c, lib/src/sv_authenticity.h, lib/src/sv_internal.h, lib/src/sv_sign.c
Takes an ONVIF Media Signing authenticity report and
copies the content to a Signed Video authenticity report.
This commits only copies the version strings and adds
an 'ONVIF' prefix to them.
=> Implements a converter for authenticity report

lib/src/sv_auth.c, lib/src/sv_common.c, lib/src/sv_onvif.c, lib/src/sv_onvif.h
If an ONVIF Media Signing SEI is detected and the library
is build with Axis Communications vendor, an ONVIF Media
Signing session is created. The trusted anchor certificate
is passed in to the new session and all queued Bitstream
Units are transferred to the new session.
Stubs have been added for compilation purpose.
=> Transfer validation to ONVIF if detected

lib/src/sv_auth.c, lib/vendors/axis-communications/sv_vendor_axis_communications.c, lib/vendors/axis-communications/sv_vendor_axis_communications_internal.h
This is needed when a validation session for the ONVIF Media
Signing is set up.
=> Adds a getter for the Axis Communications root CA

tests/check/test_helpers.c, tests/check/test_helpers.h, tests/check/test_stream.c, tests/check/test_stream.h
Unnecessary includes and absolute paths have been removed.
=> Updates include paths in test helper functions

lib/plugins/threaded-signing/plugin.c, lib/plugins/unthreaded-signing/plugin.c, lib/src/includes/signed_video_openssl.h, lib/src/legacy/legacy_auth.c, lib/src/legacy/legacy_common.c, lib/src/legacy/legacy_tlv.c, lib/src/sv_auth.c, lib/src/sv_authenticity.c, lib/src/sv_authenticity.h, lib/src/sv_common.c, lib/src/sv_internal.h, lib/src/sv_openssl.c, lib/src/sv_openssl_internal.h, lib/src/sv_sign.c, lib/src/sv_tlv.c, lib/src/sv_tlv.h, lib/vendors/axis-communications/sv_vendor_axis_communications.c, tests/check/check_signed_video_auth.c, tests/check/check_signed_video_sign.c, tests/check/test_helpers.c
When bringing in ONVIF Media Signing as a submodule
some functions share the same name. This will cause
multiple definitions if building the library with a
populated submodule, like FilePlayer will.
This commit prepends internal functions with "sv_"
to make names unique. This only applies to function
names common to ONVIF Media Signing.
=> Renames internal files

lib/src/meson.build, lib/src/sv_auth.c, lib/src/sv_authenticity.h, lib/src/sv_internal.h, lib/src/sv_onvif.c, lib/src/sv_onvif.h, lib/src/sv_sign.c, meson.build, tests/check/check_signed_video_auth.c, tests/check/check_signed_video_sign.c, tests/check/meson.build
The meson build structure has been updated to support ONVIF
Media Signing, either through a submodule or if installed
separately.
Includes have been updated and tests can now run if ONVIF
Media Signing code is present.
=> Includes ONVIF Media Signing if present

lib/src/sv_sign.c
This solves the warning -Werror=stringop-truncation.
The structures are identical in length, so it is fine to simply
copy all the content even though there are null-terminated
characters.
=> Fix compile error if warning treated as error

lib/src/includes/signed_video_common.h, lib/src/sv_common.c, tests/check/check_signed_video_common.c
There is a check for version mismatch between signing and
validation. If the stream has been signed with a newer version
than what is used when validating the validation result cannot
be guaranteed. The reason is that it is not possible to be
forward compatible.
However, if the change is minor, like when the patch number
only has changed, it should still be possible to trust the
result.
This commit checks only major and minor for version mismatch.
=> Changes behavior when comparing versions

lib/src/sv_auth.c, lib/src/sv_common.c, tests/check/check_signed_video_auth.c
Removes an assert, since hash algo will never be known if the
stream was signed with ONVIF Media Signing.
Removes a double free of the ONVIF Media Signing session.
Updates a validation test w.r.t. presence of ONVIF Media Signing
code.
=> Fixes tests to pass if Media Signing code is present

lib/plugins/threaded-signing/plugin.c
If ONVIF Media Signing is known (installed or present in the submodule)
the threaded signing plugin should pass on all operations to the
threaded plugin in media-signing-framework. This ensures that only one
thread for signing is setup, and that thread is "controlled" from
media-signing-framework.
NOTE: that using the plugin in media-signing-framework has nothing to
do whether the stream has been signed with ONVIF Media Signing format
or not.
=> Passes on threaded signing plugin if Media Signing is known

lib/vendors/axis-communications/sv_vendor_axis_communications.c, lib/vendors/axis-communications/sv_vendor_axis_communications_internal.h
Adds a function to retrieve the certificate chain during ONVIF setup.
=> Add getter for certificate chain for ONVIF initialization

lib/src/sv_internal.h, lib/src/sv_sign.c
Adds private key members signed_video_t struct to use  in ONVIF
initialization.
=> Adds private key members signed_video_t struct

lib/src/sv_internal.h, meson.build
Includes ONVIF Media Signing support (v1.0.0).
=> Bumps version to v2.1.0

lib/plugins/README.md, lib/src/sv_auth.c, lib/src/sv_internal.h, meson.build
If the library was built without any vendor (Axis) the
authentication side tried to create an ONVIF Media Signing
session when it should not. This commit fixes that.
In addition a minor spell change of GLib has been made.
The version has been changed to v2.1.1.
=> Fixes bug if lib is not built with a vendor

lib/src/includes/signed_video_auth.h, lib/src/legacy/legacy_tlv.c, lib/src/sv_authenticity.c, lib/src/sv_internal.h, lib/src/sv_sign.c, lib/src/sv_tlv.c, tests/check/check_signed_video_auth.c
Currently the SEI is associated with only one timestamp which
is the first Bitstream Unit of the (partial) GOP. In normal case
the I-frame. This means that, in neither the latest nor the
accumulated validation results, a correct time span for the
validated video can be displayed. By adding also an end timestamp
this can be achieved.
=> Adds a timestamp to the SEI TLV

tests/check/check_signed_video_auth.c, tests/check/test_helpers.c
this commit increments the timestamp for primary slices.
Tests now verify that the end_timestamp is larger than the
start_timestamp.
=> Instead of setting the same timestamp all the time

lib/src/sv_common.c, lib/src/sv_internal.h, lib/src/sv_sign.c
To be able to support signing multiple GOPs the library
has to manage unsigned SEIs. This means that the queue
of SEIs can have some already completed SEIs as well as
SEIs waiting for the signature to be completed.
This commit changes the behavior slightly when getting
SEIs.
=> Allows for unsigned SEIs

lib/src/includes/signed_video_sign.h, lib/src/sv_common.c, lib/src/sv_internal.h, lib/src/sv_sign.c, tests/check/check_signed_video_sign.c, tests/check/test_helpers.c, tests/check/test_stream.c
Through the API signed_video_set_signing_frequency(...) the user
can specify how often GOPs should be signed. Unsigned GOPs will
still produce SEIs, but without signatures. These SEIs are
hashed like normal frames and eventually signed with the final
SEI.
A test has been added for signing multiple GOPs.
=> Implements support for signing multiple GOPs

tests/check/check_signed_video_auth.c, tests/check/test_stream.c, tests/check/test_stream.h
Currently all tests are disabled since validation has not yet
been implemented and the code ends up in a dead lock.
A new test function to pop complete GOPs instead of counting
items has been added.
=> Adds tests for signing multiple GOPs

lib/src/sv_bu_list.c, lib/src/sv_internal.h
The process is completely linear independant of failure, hence it
can safely be removed.
=> Removes unnecessary member taken_ownership_of_bu

lib/src/sv_auth.c, lib/src/sv_tlv.c, lib/src/sv_tlv.h
instead of explicit function for optional tags.
=> Use generic sv_tlv_find_and_decode_tags()

lib/src/sv_auth.c, lib/src/sv_tlv.c, tests/check/check_signed_video_auth.c
This commit change the behavior to decode the optional tags in
a SEI when being registered. After that, the signature is
verified.
Further, to avoid the risk of reading the same Public key twice
the Public key is not updated if it has changed. This is a
security precaution since change of key should never be allowed.
=> Decodes SEIs at registration

lib/src/sv_auth.c, lib/src/sv_internal.h
This flag makes sure to avoid updating authenticity reports
upon unsigned SEIs.
Further, a counter has been added to avoid running into a
deadlock.
=> Adds validation flag waiting_for_signature

lib/src/sv_auth.c, lib/src/sv_internal.h
There is a more efficient way of detecting the BU hash that
also represents a linked hash. The first pending item should
by design be the linked hash.
=> Removes the used_for_linked_hash flag

lib/src/sv_auth.c
The computation should be done when there is a signed SEI. If
the first validation fails due to an outdated SEI pending BUs
have to be re-computed.
=> Move computing pending BUs into while loop

lib/src/sv_auth.c, lib/src/sv_internal.h
This makes the function
set_validation_status_of_pending_items_used_in_gop_hash obsolete,
hence is removed.
=> Use function mark_associated_items

lib/src/sv_auth.c, lib/src/sv_common.c, tests/check/check_signed_video_auth.c
The signing side has been updated to send correct number of hashed
BUs. Also, SEI association on the validation side is removed if
a lost SEI was detected, or if the first validation failed.
=> Validates intact stream signed with multiple GOPs

lib/src/sv_auth.c, lib/src/sv_internal.h
This helps in handling an arbitrary amount of wraparound, which
will be implemented.
The commit also has minor changes wher a helper member gop_info
is added.
=> Makes latest_validated_gop int64_t

lib/src/sv_auth.c, lib/src/sv_internal.h
This will replace the boolean has_lost_sei to be able to
handle SEIs that are in the wrong order.
=> Adds a new validation flag: num_lost_seis

lib/src/sv_auth.c, lib/src/sv_internal.h
This can happen if SEIs are re-ordered, session reset on camera,
or if there are SEIs in the beginning of a session that belongs to
a previous part of the stream.
Adds a new sei_in_sync validation flag and a function to check if
a hash is empty.
=> Can now handle negative num_lost_seis

lib/src/sv_authenticity.c, lib/src/sv_common.c, tests/check/check_signed_video_auth.c
Affects accumulated auth report, gop_info and validation flags.
The authenticity report "Signature present" is now only shown
once, which affects for example file scrubbing. Tests have been
updated accordingly.
=> Completes some struct resets

lib/src/sv_auth.c, lib/src/sv_common.c, lib/src/sv_internal.h, tests/check/check_signed_video_auth.c
Two members have been removed since they are redundant. These
are has_lost_sei and partial_gop_is_synched.
This change breaks file scrubbing forward. Therefore, these tests
have been disabled until solved.
=> Removes redundant code

lib/src/sv_auth.c, lib/src/sv_common.c, lib/src/sv_internal.h, tests/check/check_signed_video_auth.c
The root cause was among the validation flags, where is_first_sei
was not updated correctly.
=> Fixes forward scrubbing

lib/src/sv_auth.c
and can therefore move the code of final stats prints into the
while loop.
=> Handles num_invalid across unsigned GOPs

lib/src/sv_auth.c, tests/check/check_signed_video_auth.c
The function verify_hashes_without_sei has been updated to handle
unsigned SEIs.
=> Enables remaining signed multiple gops tests

lib/src/sv_auth.c, lib/src/sv_internal.h
It is not needed since there is a separate mechanism
to synchronize the first SEI.
=> Removes lost_start_of_gop

lib/src/sv_auth.c
Removes stats update since it is done outside this function.
Also, marking only first item if link is incorrect is also done
outside this function.
=> Simplifies verify_hashes_with_hash_list

lib/src/sv_bu_list.c, lib/src/sv_common.c, lib/src/sv_internal.h
If hashing of a Bitstream Unit is done on data without emulation
prevention bytes, that is, after them being removed, that data
is stored in a separate memory. This memory has to be copied as
well. This is critical for signing multiple GOPs to work on the
unsigned SEIs in the beginning of a session.
=> Correctly copies bu_info_t after processing at validation

lib/src/sv_auth.c
When in validation and the algorithm tries to synchronize
the SEI, reverse actions are done if syncing fails. For
unsigned SEIs the temporary operations are NOT done on
tmp_validation_status, but on validation_status_if_sei_ok.
This commit applies SEI update operations correctly for
unsigned SEIs.
=> Updates unsigned SEIs properly

lib/src/sv_auth.c, lib/src/sv_internal.h, lib/src/sv_tlv.c
This makes it easier to track wraparounds etc. Note that the
value is still stored as an uint32_t in the TLV.
=> Make current_partial_gop int64_t

lib/src/sv_auth.c, lib/src/sv_common.c, lib/src/sv_internal.h, lib/src/sv_tlv.c
The decoded partial GOP counter is stored for later use.
Currently current_partial_gop is updated right after decode,
but later it will be updated after validation based on the
result. There could for example be missing SEIs or the SEIs
might not be synchronized.
=> Adds next_partial_gop counter

lib/src/sv_auth.c, lib/src/sv_common.c, lib/src/sv_internal.h
When validating and decoding the procedure has now
changed to look forward rather than backward. The
member current_partial_gop now reflects the GOP
number that currently has been validated. It is
updated after a validation has been performed,
either with next_partial_gop or incremented if
a GOP has been lost.
The member latest_validated_gop is no longer
used, and therefore removed.
=> Removes latest_validated_gop

lib/src/sv_auth.c, tests/check/check_signed_video_auth.c
When trying to synchronize SEIs situations when validating
without a SEI to close a gap can occur. In such a case, it
should select and validate at least one BU. Otherwise, an
endless loop can occur.
This commit affects one test,
fast_forward_stream_without_reset, which temporarily has been
changed until SEI synchronization has been separated from
first validation.
=> Forces verify_without_sei to validate at least one BU

lib/src/sv_auth.c, tests/check/check_signed_video_auth.c
The sei_in_sync is only updated in one place and only if it
was not in sync before.
This solves two previous disabled tests, but fails a new one,
which has been disabled for now.
=> Computes SEI synchronization seperately

lib/src/sv_auth.c
The special case where a partial GOP is successfully validated,
but the SEI is not should return success. A failing signature
verification could be due to a bit flip of the SEI or a wrongly
set Public key. All the content could still be correct for
matching the GOP. This is in particular important when the SEI
is not in sync.
=> Verifying with SEI returns OK also if SEI is not

lib/src/sv_auth.c, tests/check/check_signed_video_auth.c
A reset made on the camera will rewind the GOP counter
which on the validation side will be detected as an
old SEI. If an old SEI is detected, but the GOP hash
is correct return success.
=> Handles reset on camera

lib/src/sv_auth.c, tests/check/check_signed_video_auth.c
Special operations on the first validation is taken if the
SEI is not in sync. All validation has to be rewinded if so.
So far this decision has been made based on the validation
results. Now it is based on wether the SEI is in sync or
not.
=> The first_validation is updated to rely on sei_in_sync

lib/src/sv_auth.c, tests/check/check_signed_video_auth.c
If multiple GOPs are validated and the validation started
being out of sync, but sync was established, the first GOP
should no longer be ignored. Therefore, perform a final
stats update after having looped through the GOPs.
=> Makes a second (final) validation stats update

lib/src/sv_auth.c, lib/src/sv_internal.h, meson.build
Hashing algorithm is by definition known is therefore set when
creating a legacy object.
Version is bumped to v2.2.3
=> Fixes a bug in validating legacy recordings

lib/src/sv_common.c, lib/src/sv_internal.h, lib/src/sv_tlv.c, meson.build
If the read TLV length parameter is too large, i.e., will make
reading outside memory, when finding a tag no tag is returned.
Further, when finding the signature tag a second time fails
the SEI is put in an error state with member is_valid.
=> Adds sanity check on TLV length

lib/src/sv_internal.h, tests/check/check_signed_video_auth.c, tests/check/check_signed_video_sign.c, tests/check/legacy_test_data.c, tests/check/test_helpers.c, tests/check/test_stream.c, tests/check/test_stream.h
A test stream can now be created with FH and following TG. The
TG is represented by 't'. That is, a GOP with frame header is
written as "ItPtPtPt".
=> Test dummy data now supports FH + TG for AV1

.github/workflows/meson-build.yml, .github/workflows/meson-full-build.yml, lib/src/includes/signed_video_auth.h, lib/src/sv_auth.c, lib/src/sv_codec_av1.c, lib/src/sv_common.c, lib/src/sv_internal.h, lib/src/sv_sign.c
For efficiency when transmitting the hash list hashing both the
FH and all TGs becomes quite costly. Therefore, one single hash
for the entire frame (FH+TGs) is generated.
The logic is similar to hashing when a NALU is split into
several parts. There is one major difference though, and that is
that for FH+TGs it is not known when to complete the ongoing
hash until the next frame has been detected.
Therefore, a helper function sv_add_ongoing_hash() that handles
frame transitions has been added.
The commit updates both the signing and the validation side
which keeps the test intact.
=> Hashes FH+TGs together
