- lib/src/signed_video_internal.h
- meson.build
Includes fix in pkgconfig generator in meson.
> Increases version to R1.0.3

- lib/src/signed_video_h26x_auth.c
- lib/src/signed_video_tlv.c
- tests/check/check_h26xsigned_auth.c
Adds a test for detecting a change in public key.
Detection is done when decoding the TLV tag.
> Detects changed public key

- lib/src/signed_video_h26x_common.c
- lib/src/signed_video_internal.h
- meson.build
- tests/check/check_signed_video_common.c
Note that the initial version character has changed from 'R' to 'v'.
This is more in line with other repos.
Main features included:
- threaded signing plugin
- less frequent metadata can now be transmitted according to a
recurrence interval defined in number of GOPs
> Upgrades version to v1.1.0

- README.md
- lib/README.md
- lib/meson.build
- lib/src/includes/sv_vendor_axis_communications.h
- lib/src/meson.build
- lib/src/signed_video_authenticity.c
- lib/src/signed_video_defines.h
- lib/src/signed_video_h26x_common.c
- lib/src/signed_video_h26x_sign.c
- lib/src/signed_video_internal.h
- lib/src/signed_video_tlv.c
- lib/src/signed_video_tlv.h
- lib/vendors/README.md
- lib/vendors/axis-communications/meson.build
- lib/vendors/axis-communications/sv_vendor_axis_communications.c
- lib/vendors/axis-communications/sv_vendor_axis_communications.h
- lib/vendors/axis-communications/sv_vendor_axis_communications_internal.h
- lib/vendors/meson.build
- meson.build
- meson_options.txt
- tests/check/check_h26xsigned_auth.c
- tests/check/check_h26xsigned_sign.c
- tests/check/signed_video_helpers.c
- tests/check/signed_video_helpers.h
- tests/test_checks.sh
Axis Communications specific code for setting and transmitting an Attestation Report.
> Adds vendor axis communications

- lib/vendors/axis-communications/sv_vendor_axis_communications.c
that takes a trusted CA and a stack of untrusted certificates as input.
Then verifies the first certificate in the chain and return SVI_VENDOR
if the verification was not successful.
> Adds new Axis helper function verify_certificate_chain

- lib/vendors/axis-communications/sv_vendor_axis_communications.c
Also adds a define for string 'Unknown' used in several places.
> Extracts serial number from the Axis attestation certificate

- lib/vendors/axis-communications/sv_vendor_axis_communications.c
and stores it in a message digest context for use when validating the public
key, used in video authenticity validation.
> Gets pubkey from Axis attestation certificate

- lib/vendors/axis-communications/sv_vendor_axis_communications.c
which in this commit is a skeleton to be filled in step-by-step.
> New Axis vendor function verify_axis_communications_public_key

- lib/vendors/axis-communications/sv_vendor_axis_communications.c
which is the form used in the signed data.
> Converts Axis public key to uncompressed Weierstrass form

- lib/vendors/axis-communications/sv_vendor_axis_communications.c
> Constructs binary raw data for Axis public key validation

- lib/src/signed_video_h26x_common.c
- lib/src/signed_video_h26x_sign.c
- lib/src/signed_video_internal.h
- lib/src/signed_video_tlv.c
Puts the signing requests in a queue one by one and gets the oldest
signing request from the queue.
> Puts the signing requests in a queue

- tests/check/meson.build
Change-Id: I5200ed8da1ee83efebb57458bcbeb24f164a253f
> Only run auth side tests if unthreaded

- lib/src/includes/signed_video_auth.h
- lib/src/includes/signed_video_common.h
- lib/src/includes/signed_video_interfaces.h
- lib/src/includes/signed_video_openssl.h
- lib/src/includes/signed_video_sign.h
- lib/src/includes/sv_vendor_axis_communications.h
> Puts public headers under extern "C" scope

- lib/src/signed_video_internal.h
- meson.build
- tests/check/check_h26xsigned_auth.c
- tests/check/check_h26xsigned_sign.c
- tests/test_checks.sh
by excluding recurrence for a number of test, where it has no
real meaning.
Also made a minor change to test_checks.sh.
Bumps version to v1.1.23.
> Reduces unittest running time

- lib/src/signed_video_h26x_auth.c
- lib/src/signed_video_h26x_nalu_list.c
- lib/src/signed_video_internal.h
- meson.build
- tests/check/check_h26xsigned_auth.c
at startup. This is a temporary fix that can handle all test cases but one.
> Validates successfully for two invalid SEIs

- lib/plugins/README.md
- lib/plugins/threaded-signing/plugin.c
- lib/plugins/unthreaded-signing/plugin.c
- lib/src/includes/signed_video_interfaces.h
- lib/src/signed_video_internal.h
- meson.build
the user should set the signing key at init.
> Initialization of threaded plugin

- lib/src/signed_video_openssl.c
This commit makes sure to assign the new hash algo to the message
digest context.
Further, does not free and create new contexts for each hash.
> Fix setting hash algo

- .github/workflows/meson-build.yml
Now compiles with threaded signing plugin as well to be able
to catch errors when threaded signing is used.
> Updates workflow

- lib/src/signed_video_h26x_common.c
- lib/src/signed_video_h26x_sign.c
- lib/src/signed_video_tlv.c
The signing side now uses the new member sign_data.
> Signing side uses sign_data

- tests/check/test_stream.c
Mainly updates descriptions and comments. Kept 'list'
as word in most places despite moving towards 'stream'.
Removed some non used code.
> Updates descriptions in test_stream.c

- tests/check/signed_video_helpers.h
Removes unused includes and updates some descriptions.
> Cleanup of signed_video_helpers.h

- tests/check/test_helpers.c
- tests/check/test_helpers.h
Local storage of private keys are made static. In addition,
various descriptions have been updated.
> Makes keys static

- tests/check/test_helpers.c
- tests/check/test_helpers.h
Some name changes and removal of unnecessary code.
> Cleanup of test_helpers

- tests/check/check_signed_video_auth.c
- tests/check/test_helpers.h
and updates various descriptions and comments.
> Removes unused code

- lib/src/includes/signed_video_sign.h
- lib/src/signed_video_h26x_sign.c
- lib/src/signed_video_tlv.c
- lib/src/signed_video_tlv.h
- tests/check/check_signed_video_sign.c
> generate golden SEI

- lib/src/signed_video_internal.h
Puts members in signed_video_t grouped as common, signing,
validation and tests.
Also updates some descriptions and comments.
> Organizes members in signed_video_t

- lib/src/signed_video_h26x_auth.c
- lib/src/signed_video_h26x_common.c
- lib/src/signed_video_internal.h
Renames has_gop_sei to has_sei in gop_state_t.
Removes version from gop_info_t, since it is never used.
> Removes and renames 2 members

- lib/src/signed_video_tlv.c
- lib/src/signed_video_tlv.h
> Refactors signed_video_tlv.h

- lib/src/signed_video_h26x_auth.c
- lib/src/signed_video_tlv.c
- lib/src/signed_video_tlv.h
This includes mostly updates of comments, but also a function
name change and variable names to use 'optional' instead of
'recurrent'.
> General cleanup in signed_video_tlv.c

- tests/check/check_signed_video_sign.c
- tests/check/test_helpers.c
- tests/check/test_helpers.h
This function checks flags and TLV content of the SEIs as well
as their sizes.
Three new members to the test setting struct has been added.
> Adds a helper function that verifies SEIs

- lib/src/legacy/legacy_tlv.c
- lib/src/signed_video_tlv.c
Under the PRINT_DECODED_SEI flag prints the content of a decoded
SEI present in the General tag. This is applied to both the current
and legacy code.
> Prints decoded information of the general tag

- lib/src/signed_video_h26x_common.c
- tests/check/check_signed_video_auth.c
- tests/check/test_stream.c
This distiguishes between 'normal' SEIs and Golden SEIs.
> Gives Golden SEIs a 'G' character

- lib/src/signed_video_h26x_auth.c
If multiple GOPs are validated in one go, the first result is
replaced by the next, hence, can hide a 'NOT OK' with a 'OK'
in the next go.
This is now solved.
> Correctly updates latest validation

- lib/src/signed_video_h26x_auth.c
Breaks at first I-frame if NAL Units have already been added to the
GOP hash.
> Do not allow the gop hash to span multiple GOPs

- tests/check/check_signed_video_auth.c
The tests file export without dangling end and public key arrives
late, are no longer meaningful. There is currently no way to make
file export without getting a dangling end and the recurrence has
been removed.
> Removes 2 auth tests

- tests/check/check_signed_video_auth.c
Now has one common comment at top of auth test file.
> Replaces redundant comments with one

- lib/src/signed_video_h26x_auth.c
Removed the `verify_hashes_with_gop_hash` API from the video
authentication process, as recursive hashing is no longer part
of the signing workflow.
> Remove `verify_hashes_with_gop_hash` API

- lib/src/signed_video_h26x_auth.c
> Remove compute_gop_hash static function

- lib/src/signed_video_h26x_auth.c
Currently has no impact since no SEIs are marked.
> Adds update function for SEIs in validation

- lib/vendors/axis-communications/sv_vendor_axis_communications.c
- tests/check/check_signed_video_sign.c
A test that verifies that the public key is not transmitted
separately, but instead in a certificate is added.
> Supports signing with Axis factory provisioning

- lib/src/signed_video_tlv.c
- tests/check/check_signed_video_auth.c
When decoding the Axis vendor tag, the public key is fetched from
the leaf certificate.
Further, a test has been added that validates a GOP using factory
provisioning.
> Adds final support for validation with Axis factory provisioning

- lib/src/sv_h26x_nalu_list.c
> Fix failing tests after file name changes

- lib/src/sv_h26x_auth.c
- lib/src/sv_h26x_common.c
- lib/src/sv_h26x_internal.h
- lib/src/sv_h26x_nalu_list.c
- lib/src/sv_h26x_nalu_list.h
- lib/src/sv_h26x_sign.c
- lib/src/sv_internal.h
- tests/check/check_signed_video_sign.c
- tests/check/test_helpers.c
- tests/check/test_stream.c
where bu is short for Bitstream Unit and can be either NALU or OBU.
> Renames h26x_nalu_t to bu_t

- lib/src/sv_h26x_auth.c
- lib/src/sv_h26x_common.c
- lib/src/sv_h26x_internal.h
- lib/src/sv_h26x_nalu_list.c
- lib/src/sv_h26x_nalu_list.h
> Renames h26x_nalu_list_item_t

- lib/src/sv_h26x_common.c
- lib/src/sv_h26x_nalu_list.c
- lib/src/sv_h26x_nalu_list.h
> Renames BU list create and free functions.

- lib/src/sv_h26x_auth.c
- lib/src/sv_h26x_nalu_list.c
- lib/src/sv_h26x_nalu_list.h
> Renames get_stats and num_pending_items

- lib/src/sv_h26x_auth.c
- lib/src/sv_h26x_nalu_list.c
- lib/src/sv_h26x_nalu_list.h
and also adds curly brackets for some if statements.
> Renames update_status

- lib/src/sv_bu_list.c
- lib/src/sv_bu_list.h
and static functions. Changes of nalu to bu.
> Renames of variables

- lib/src/sv_bu_list.c
- lib/src/sv_h26x_auth.c
- lib/src/sv_h26x_common.c
- lib/src/sv_h26x_internal.h
New name is |bu|.
Further, all places where bu_info_t is used is now named |bu|.
> Renames bu_info_t member of bu_list_item_t

- lib/src/legacy/legacy_h26x_common.c
- lib/src/sv_bu_list.c
- lib/src/sv_h26x_common.c
- lib/src/sv_h26x_internal.h
- lib/src/sv_h26x_sign.c
- tests/check/test_stream.c
In addition, renames the SignedVideoFrameType enum types.
> Renames bu_info_t member nalu_typ to bu_type

- lib/src/legacy/legacy_h26x_auth.c
- lib/src/legacy_validation.h
- lib/src/sv_authenticity.c
- lib/src/sv_bu_list.c
- lib/src/sv_h26x_auth.c
- lib/src/sv_h26x_common.c
- lib/src/sv_h26x_sign.c
- lib/src/sv_openssl.c
- lib/src/sv_tlv.c
Variables, functions and comments using 'nalu' in various forms
where it can also refer to AV1 OBUs have been changed to 'bu' or
more explicit Bitstream Unit.
> Name changes in c-files

- lib/src/includes/signed_video_auth.h
- lib/src/includes/signed_video_common.h
- lib/src/includes/signed_video_helpers.h
- lib/src/includes/signed_video_sign.h
- lib/src/legacy_validation.h
- lib/src/sv_authenticity.c
- lib/src/sv_bu_list.h
- lib/src/sv_h26x_auth.c
- lib/src/sv_h26x_common.c
- lib/src/sv_h26x_sign.c
- lib/src/sv_internal.h
- lib/src/sv_tlv.c
- tests/check/check_signed_video_auth.c
- tests/check/test_helpers.c
- tests/check/test_helpers.h
In addition some more description cleanup etc.
> Further name changes of members with nalu

- tests/check/check_signed_video_auth.c
As a preparation for future use when signing partial and multiple
GOPs using different file export test streams. Also includes
scrubbing in "sign partial GOPs" tests.
The validation_stream no longer consumes the items to be able to
scrub a file.
> Changes mimic_file_export

- lib/src/sv_auth.c
- lib/src/sv_common.c
- lib/src/sv_internal.h
- lib/src/sv_sign.c
- lib/src/sv_tlv.c
Then naming now reflects partial GOPs rather than (full) GOPs.
> Renames some gop_info_t members

- lib/src/sv_bu_list.c
- lib/src/sv_bu_list.h
The function finds the next hashable item in the list.
> Adds a helper function for bu_list_item

- lib/src/sv_auth.c
- tests/check/check_signed_video_auth.c
The function now takes an input for skipping BUs.
Consider for example a case where one SEI has been lost and
partial GOPs are signed. It can then happen that there are no
I-frames at all, and marking all of them as invalid will force
the next validation with the SEI to have no BUs at all.
Therefore, mark only as few as possible to save some for the SEI.
This solves some known issues where validation fails; See tests.
> Updates verify_hashes_without_sei()

- lib/src/sv_auth.c
- tests/check/check_signed_video_auth.c
and makes sure to update the link hash also on P-frames.
> Turns on validation tests for partial GOPs

- lib/src/sv_common.c
- lib/src/sv_internal.h
- lib/src/sv_sign.c
Simplify hash members among various hashes
> Simplify hash handling

- lib/src/sv_onvif.c
- lib/src/sv_onvif.h
- lib/src/sv_sign.c
Change-Id: I4a3c3af50b6653b7ee03bc0033463db552009800
> Updates setters for Golden Sei if Onvif available

- lib/src/sv_sign.c
Change-Id: I6ca229fd8b1a598a8adc2544232b0b0b08f3cc0b
> Fixes the setters for golden sei

- lib/src/sv_common.c
- lib/src/sv_internal.h
Adds Onvif Sei uuid for Onvif Sei detection
Change-Id: Ia865d8a895aaad62c0a2a7a036cbdd0e0aa2228d
> Adds Onvif Sei uuid

- lib/src/sv_authenticity.c
when converting the authenticity report.
> Copies vendor_info to product_info

- lib/src/sv_onvif.c
- lib/src/sv_onvif.h
- lib/src/sv_sign.c
Adds a stub for the low bitrate mode setter.
> Passes on authenticity level to ONVIF Media Signing if active

- lib/src/sv_authenticity.c
- lib/src/sv_onvif.h
Adds stubs for necessary typedefs.
> Transfers latest validation from ONVIF to Signed Video

- lib/src/sv_common.c
- lib/src/sv_internal.h
- lib/src/sv_onvif.c
- lib/src/sv_onvif.h
- lib/vendors/axis-communications/sv_vendor_axis_communications.c
Updated Signed Video create, reset, and free APIs for onvif.
> Update Signed Video create, reset, and free APIs

- lib/src/sv_authenticity.c
- lib/src/sv_onvif.h
Adds stubs for necessary typedef.
> Transfers accumulated validation from ONVIF to Signed Video

- lib/src/sv_internal.h
- lib/src/sv_sign.c
Placeholders for hash algo and vendor info, since those require
additional changes.
> Adds a function that ports all settings to ONVIF Media Signing

- lib/src/sv_sign.c
Adds a helper function to convert product_info to vendor_info.
> Ports product info to Media Signing

- lib/src/meson.build
- meson.build
- tests/check/check_signed_video_auth.c
- tests/check/check_signed_video_common.c
- tests/check/check_signed_video_sign.c
- tests/check/meson.build
The shared library is now created from root meson.
The lib/src/ directory is now added as include directory
to avoid absolute paths from root.
Tests have been updated with the changes.
> Restructures meson

- lib/plugins/threaded-signing/plugin.c
- lib/plugins/unthreaded-signing/plugin.c
Also, makes a global variable static.
> Prepends structs in plugin with 'sv_'

- lib/src/sv_onvif.c
- lib/src/sv_onvif.h
Adds signing key pairs API for ONVIF initialization
> Adds ONVIF signing key pairs API

- lib/src/sv_internal.h
- lib/src/sv_sign.c
- lib/vendors/axis-communications/sv_vendor_axis_communications.c
Adds a function that initializes ONVIF when it is available.
> Adds function to initialize ONVIF

- lib/src/sv_internal.h
- tests/check/check_signed_video_auth.c
- tests/check/check_signed_video_sign.c
- tests/check/test_helpers.c
Added and modified tests to verify that ONVIF signing and authentication
work as expected.
> Added and modified tests to verify ONVIF signing and authentication

- lib/src/sv_sign.c
These two functions are always called right after each other.
They have been combined into one function
generate_sei_and_add_to_buffer(...).
Also, the variable 'payload' has been changed to 'sei' in this
function since it actually generates a complete SEI and not
just the payload of the SEI.
> Merges generate_sei and add_payload_to_buffer

- lib/src/sv_auth.c
The next available SEI is searched for in several places. It is
only necessary to do it once, when preparing for validation.
This commit passes that SEI on for further validation.
> Get next SEI only once

- lib/src/sv_auth.c
Removes redundant code since the function is only entered upon
a successful signature verification.
> Updates verify_hashes_with_hash_list with validation status

- lib/src/sv_auth.c
when removing sei association and/or validating without sei.
> Resets validation_status_if_sei_ok

- lib/src/sv_auth.c
Since items are already associated with a sei there is no longer
a need to check for end of GOPs etc.
> Removes unused parts in verify_hashes_with_hash_list

- lib/src/sv_auth.c
Removes some dead code based on that as well.
> Makes sure tmp_validation_status of SEIs is set

- lib/src/sv_auth.c
When validating unsigned GOPs the final validation (with a signed
SEI) has to recursively update the result of previous GOPs.
This new function solves that.
> Adds a function to that marks items associated with a SEI

- lib/src/sv_auth.c
This function is no longer needed since information is
extracted when SEIs are registered. The only thing to check is
for is presence of a Public key (if session is signed).
> Remove is_recurrent_data_decoded

- lib/src/sv_auth.c
Since SEIs are (partially) decoded and hashed upon registration
there is no longer a need to decode and hash Golden SEIs
separately.
> Simplifies Golden SEI validation

- lib/src/sv_auth.c
- tests/check/check_signed_video_auth.c
Corresponding tests have been activated.
> Signing multiple GOPs can now handle incorrect P-frames

- lib/src/sv_auth.c
Some variable renaming and changes to use int64_t.
> Determines wraparounds in partial GOP counter

- lib/src/sv_auth.c
- lib/src/sv_bu_list.c
- lib/src/sv_bu_list.h
- lib/src/sv_internal.h
It has not been used yet.
Also adds a helper function to add a missing item after the last
item in a partial GOP.
> Adds validation flag: lost_start_of_gop

- lib/src/sv_auth.c
Moves out some of the logic that should be handled generically.
> Refactors verify_hashes_with_sei slightly

- lib/src/sv_common.c
Also, updates the "Received ..." debug print.
> Prints correct character when SEI is not signed

- lib/src/sv_internal.h
- meson.build
Includes support for signing multiple GOPs.
> Bumps version to v2.2.0

- lib/src/sv_bu_list.c
- lib/src/sv_bu_list.h
The function is no longer used anywhere in the code.
> Removes bu_list_remove_missing_items

- tests/check/check_signed_video_auth.c
The test now modify one P-frame of the first GOP, emphasizing
the tricky part to validate a tampering case before the SEIs
have been synchronized.
The test has been adjusted to pass, but will be changed when
solved properly.
> Changes test modify_one_p_frame

- lib/src/sv_auth.c
The function is a one-liner and only used in one place. No need
to have a function for it.
> Removes reset_linked_hash
